# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd45d1f49906a1fad9328bbf0e040fd936c4c165396bb7276f46954335443db55f4b7331ac351127f112eaaacfe5e53be13424544f40e10fb736bcafd3d24f2e

test:
  secret_key_base: 324cddb95af9786ad320ac1ed754037d6ab1d9b1edeb2493e0bf76974803fa45f63b8ee52db2d3a5c701e25399b1c8174bb8e87cb8309fbc3d06f4f8ab7818dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
