User.create! email:             'admin@admin.com',
             password:          '12345678',
             name:              'admin',
             surname:           'admin',
             phone_number:      '12345678',
             city:              'admin',
             address:           'admin',
             pending_approval:  false,
             ban_user:          false,
             social_network:    false,
             admin:             true
